[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"
