name = "VlasovTT"
uuid = "fd69607e-dff2-4fde-869b-4f0482a672e0"
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Quantics = "87f76fb3-a40a-40c9-a63c-29fcfe7b7547"
QuanticsGrids = "634c7f73-3e90-4749-a1bd-001b8efc642d"
QuanticsTCI = "b11687fd-3a1c-4c41-97d0-998ab401d50e"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TensorCrossInterpolation = "b261b2ec-6378-4871-b32e-9173bb050604"

[compat]
HDF5 = "0.17.2"
Revise = "3.12.3"
